services:
  scms-backend-postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  scms-backend-redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
